sudo: required
services:
  - docker

before_install:
  - docker build -t pkherrera/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true  pkherrera/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Docker-react-env-1"
  buket_name: "elasticbeanstalk-us-east-1-858800035406"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
